name: Lint

# Conditions de déclenchement de l'action
on:
  pull_request:
    branches:
      - dev 
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Check lint
    steps:
    - uses: actions/checkout@v3
    # Commandes à lancer lors de l'action
    - run: npm install
    - run: npm run lint

